/**
 * Bootstrap Command
 * Full project generation (ClaudeKit style)
 * Invokes: researcher → planner → coder → tester
 */

import chalk from 'chalk';
import ora from 'ora';
import { researcherAgent } from '../agents/research/researcher.js';
import { plannerAgent } from '../agents/development/planner.js';
import { mkdirSync, existsSync, writeFileSync } from 'fs';
import { join } from 'path';

export async function bootstrapCommand(projectName: string, template?: string): Promise<void> {
    console.log(chalk.cyan.bold('\n🚀 Bootstrap New Project...\n'));
    console.log(chalk.gray(`Project: ${projectName}`));
    console.log(chalk.gray(`Template: ${template || 'default'}\n`));

    const projectPath = join(process.cwd(), projectName);

    // Step 1: Create project directory
    const spinner = ora('Step 1/4: Creating project structure...').start();

    try {
        if (existsSync(projectPath)) {
            spinner.fail(`Directory ${projectName} already exists`);
            return;
        }

        mkdirSync(projectPath, { recursive: true });
        mkdirSync(join(projectPath, 'src'), { recursive: true });
        mkdirSync(join(projectPath, 'tests'), { recursive: true });
        mkdirSync(join(projectPath, 'docs'), { recursive: true });
        mkdirSync(join(projectPath, 'plans'), { recursive: true });
        mkdirSync(join(projectPath, '.gemini-kit'), { recursive: true });

        spinner.succeed('Project structure created');

        // Step 2: Research best practices
        spinner.start('Step 2/4: Researching best practices...');

        const ctx = {
            projectRoot: projectPath,
            currentTask: `setup ${template || 'TypeScript'} project: ${projectName}`,
            sharedData: {} as Record<string, unknown>,
        };

        researcherAgent.initialize(ctx);
        const researchResult = await researcherAgent.execute();
        researcherAgent.cleanup();

        spinner.succeed('Research complete');

        // Step 3: Create implementation plan
        spinner.start('Step 3/4: Creating implementation plan...');

        ctx.sharedData = { research: researchResult.data };
        plannerAgent.initialize(ctx);
        await plannerAgent.execute();
        plannerAgent.cleanup();

        spinner.succeed('Plan created');

        // Step 4: Generate base files
        spinner.start('Step 4/4: Generating base files...');

        // Create package.json
        const packageJson = {
            name: projectName,
            version: '0.1.0',
            type: 'module',
            scripts: {
                dev: 'tsx watch src/index.ts',
                build: 'tsc',
                test: 'vitest',
            },
            devDependencies: {
                typescript: '^5.0.0',
                tsx: '^4.0.0',
                vitest: '^2.0.0',
            },
        };

        writeFileSync(
            join(projectPath, 'package.json'),
            JSON.stringify(packageJson, null, 2)
        );

        // Create tsconfig.json
        const tsconfig = {
            compilerOptions: {
                target: 'ES2022',
                module: 'NodeNext',
                moduleResolution: 'NodeNext',
                strict: true,
                outDir: 'dist',
            },
            include: ['src'],
        };

        writeFileSync(
            join(projectPath, 'tsconfig.json'),
            JSON.stringify(tsconfig, null, 2)
        );

        // Create index.ts
        writeFileSync(
            join(projectPath, 'src', 'index.ts'),
            `/**
 * ${projectName}
 * Generated by gemini-kit bootstrap
 */

console.log('Hello from ${projectName}!');
`
        );

        // Create README
        writeFileSync(
            join(projectPath, 'README.md'),
            `# ${projectName}

Generated by gemini-kit bootstrap.

## Getting Started

\`\`\`bash
cd ${projectName}
pnpm install
pnpm dev
\`\`\`
`
        );

        // Create .gemini-kit config
        writeFileSync(
            join(projectPath, '.gemini-kit', 'context.json'),
            JSON.stringify(
                {
                    projectName,
                    createdAt: new Date().toISOString(),
                    template: template || 'default',
                },
                null,
                2
            )
        );

        spinner.succeed('Base files generated');

        console.log(chalk.green.bold('\n✅ Project bootstrapped successfully!\n'));
        console.log(chalk.white('Next steps:'));
        console.log(chalk.gray(`  cd ${projectName}`));
        console.log(chalk.gray('  pnpm install'));
        console.log(chalk.gray('  gk cook "your first feature"'));
    } catch (error) {
        spinner.fail(`Bootstrap failed: ${error}`);
    }
}
